In [1]:
import torch
import numpy as np

from scipy.optimize import linear_sum_assignment

In [2]:
BATCH_SIZE = 32
H = W = 64
C = 768

In [4]:
x = torch.randn((BATCH_SIZE, H*W, C)) # B x HW x C
cls_token = torch.zeros((1, 1, C))

x = torch.cat((cls_token.expand(x.shape[0], -1, -1), x), dim=1) # cls_token 1x1x768, x = BS x HW x 768
x.shape


torch.Size([32, 4097, 768])

In [2]:
cost = np.array([[4, 1, 3], [2, 0, 5], [3, 2, 2]])
row_ind, col_ind = linear_sum_assignment(cost)
row_ind, col_ind

(array([0, 1, 2]), array([1, 0, 2]))

In [4]:
S_forward = torch.randn((3, 3))
indices_forward = [torch.as_tensor(index, dtype=torch.int64, device='cpu') for index in ([0, 1,2], [0, 1, 2])]
sim_scores_f = S_forward[indices_forward[0], indices_forward[1]]
sim_scores_f.shape

torch.Size([3])

In [5]:
sim_scores_f

tensor([ 1.0530, -0.3442, -0.0090])

In [6]:
S_forward

tensor([[ 1.0530, -0.7875, -0.3523],
        [-0.0480, -0.3442, -0.9462],
        [-0.1644, -0.5417, -0.0090]])